/* eslint-disable */
// AUTO-GENERATED by scripts/generate-types.ts — do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      activity_log: {
        Row: {
          id: string
          user_id: string
          action: string
          target_id: string | null
          target_type: string | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          action: string
          target_id: string | null
          target_type: string | null
          metadata: Json | null
          created_at?: string
        }
        Update: {
          id?: string | null
          user_id?: string | null
          action?: string | null
          target_id?: string | null
          target_type?: string | null
          metadata?: Json | null
          created_at?: string | null
        }
        Relationships: []
      }
      blocks: {
        Row: {
          blocker_id: string
          blocked_id: string
        }
        Insert: {
          blocker_id: string
          blocked_id: string
        }
        Update: {
          blocker_id?: string | null
          blocked_id?: string | null
        }
        Relationships: []
      }
      card_positions: {
        Row: {
          id: string
          user_id: string
          node_id: string
          folder_id: string | null
          pos_x: number
          pos_y: number
          width: number
          height: number
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          node_id: string
          folder_id: string | null
          pos_x?: number
          pos_y?: number
          width?: number
          height?: number
          updated_at?: string
        }
        Update: {
          id?: string | null
          user_id?: string | null
          node_id?: string | null
          folder_id?: string | null
          pos_x?: number | null
          pos_y?: number | null
          width?: number | null
          height?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      categorization_suggestions: {
        Row: {
          id: string
          user_id: string
          node_id: string
          suggested_folder_name: string | null
          suggested_tag_labels: any[]
          reason: string | null
          status: string
          created_at: string
          reviewed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          node_id: string
          suggested_folder_name: string | null
          suggested_tag_labels?: any[]
          reason: string | null
          status?: string
          created_at?: string
          reviewed_at: string | null
        }
        Update: {
          id?: string | null
          user_id?: string | null
          node_id?: string | null
          suggested_folder_name?: string | null
          suggested_tag_labels?: any[] | null
          reason?: string | null
          status?: string | null
          created_at?: string | null
          reviewed_at?: string | null
        }
        Relationships: []
      }
      categorization_suggestions_backup_20260927: {
        Row: {
          id: string | null
          user_id: string | null
          node_id: string | null
          suggested_folder_name: string | null
          suggested_tag_labels: any[] | null
          reason: string | null
          status: string | null
          created_at: string | null
          reviewed_at: string | null
        }
        Insert: {
          id: string | null
          user_id: string | null
          node_id: string | null
          suggested_folder_name: string | null
          suggested_tag_labels: any[] | null
          reason: string | null
          status: string | null
          created_at: string | null
          reviewed_at: string | null
        }
        Update: {
          id?: string | null
          user_id?: string | null
          node_id?: string | null
          suggested_folder_name?: string | null
          suggested_tag_labels?: any[] | null
          reason?: string | null
          status?: string | null
          created_at?: string | null
          reviewed_at?: string | null
        }
        Relationships: []
      }
      causes: {
        Row: {
          id: string
          cause_type: string
          created_by: string
          created_at: string
          metadata: Json | null
          folder_grant_id: string | null
        }
        Insert: {
          id?: string
          cause_type: string
          created_by: string
          created_at?: string
          metadata: Json | null
          folder_grant_id: string | null
        }
        Update: {
          id?: string | null
          cause_type?: string | null
          created_by?: string | null
          created_at?: string | null
          metadata?: Json | null
          folder_grant_id?: string | null
        }
        Relationships: []
      }
      direct_chats: {
        Row: {
          id: string
          user_1_id: string
          user_2_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_1_id: string
          user_2_id: string
          created_at?: string
        }
        Update: {
          id?: string | null
          user_1_id?: string | null
          user_2_id?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      edges: {
        Row: {
          id: string
          node_id: string | null
          user_id: string
          cause_id: string
          sender_id: string | null
          direction: string
          depth: number | null
          created_at: string
          permission: string
          folder_id: string | null
        }
        Insert: {
          id?: string
          node_id: string | null
          user_id: string
          cause_id: string
          sender_id: string | null
          direction: string
          depth: number | null
          created_at?: string
          permission?: string
          folder_id: string | null
        }
        Update: {
          id?: string | null
          node_id?: string | null
          user_id?: string | null
          cause_id?: string | null
          sender_id?: string | null
          direction?: string | null
          depth?: number | null
          created_at?: string | null
          permission?: string | null
          folder_id?: string | null
        }
        Relationships: []
      }
      external_items_map: {
        Row: {
          id: string
          external_source_id: string
          external_id: string
          node_id: string
          created_at: string
        }
        Insert: {
          id?: string
          external_source_id: string
          external_id: string
          node_id: string
          created_at?: string
        }
        Update: {
          id?: string | null
          external_source_id?: string | null
          external_id?: string | null
          node_id?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      external_sources: {
        Row: {
          id: string
          name: string
          base_url: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          base_url: string
          created_at?: string
        }
        Update: {
          id?: string | null
          name?: string | null
          base_url?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      folder_admins: {
        Row: {
          folder_id: string
          user_id: string
          granted_by: string
        }
        Insert: {
          folder_id: string
          user_id: string
          granted_by: string
        }
        Update: {
          folder_id?: string | null
          user_id?: string | null
          granted_by?: string | null
        }
        Relationships: []
      }
      folder_edges: {
        Row: {
          id: string
          node_id: string
          folder_id: string
          created_at: string
          added_by: string | null
        }
        Insert: {
          id?: string
          node_id: string
          folder_id: string
          created_at?: string
          added_by: string | null
        }
        Update: {
          id?: string | null
          node_id?: string | null
          folder_id?: string | null
          created_at?: string | null
          added_by?: string | null
        }
        Relationships: []
      }
      folder_grants: {
        Row: {
          id: string
          folder_id: string
          grantee_id: string
          permission: string
          granted_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          folder_id: string
          grantee_id: string
          permission: string
          granted_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string | null
          folder_id?: string | null
          grantee_id?: string | null
          permission?: string | null
          granted_by?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      folder_ratings: {
        Row: {
          id: string
          folder_id: string
          user_id: string
          score: number
          updated_at: string
        }
        Insert: {
          id?: string
          folder_id: string
          user_id: string
          score: number
          updated_at?: string
        }
        Update: {
          id?: string | null
          folder_id?: string | null
          user_id?: string | null
          score?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      folder_tree: {
        Row: {
          folder_id: string
          ancestor_id: string
          depth: number
        }
        Insert: {
          folder_id: string
          ancestor_id: string
          depth: number
        }
        Update: {
          folder_id?: string | null
          ancestor_id?: string | null
          depth?: number | null
        }
        Relationships: []
      }
      folders: {
        Row: {
          id: string
          name: string
          owner_id: string
          parent_folder_id: string | null
          deleted_at: string | null
          created_at: string
          is_project: boolean
          color_hex: string
          description: string | null
          system_kind: string | null
          trash_batch_id: string | null
        }
        Insert: {
          id?: string
          name: string
          owner_id: string
          parent_folder_id: string | null
          deleted_at: string | null
          created_at?: string
          is_project?: boolean
          color_hex: string
          description: string | null
          system_kind: string | null
          trash_batch_id: string | null
        }
        Update: {
          id?: string | null
          name?: string | null
          owner_id?: string | null
          parent_folder_id?: string | null
          deleted_at?: string | null
          created_at?: string | null
          is_project?: boolean | null
          color_hex?: string | null
          description?: string | null
          system_kind?: string | null
          trash_batch_id?: string | null
        }
        Relationships: []
      }
      friend_invites: {
        Row: {
          id: string
          from_user_id: string
          to_user_id: string | null
          to_email: string
          created_at: string
        }
        Insert: {
          id?: string
          from_user_id: string
          to_user_id: string | null
          to_email: string
          created_at?: string
        }
        Update: {
          id?: string | null
          from_user_id?: string | null
          to_user_id?: string | null
          to_email?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      group_admins: {
        Row: {
          group_id: string
          user_id: string
          granted_by: string
        }
        Insert: {
          group_id: string
          user_id: string
          granted_by: string
        }
        Update: {
          group_id?: string | null
          user_id?: string | null
          granted_by?: string | null
        }
        Relationships: []
      }
      group_members: {
        Row: {
          group_id: string
          user_id: string
        }
        Insert: {
          group_id: string
          user_id: string
        }
        Update: {
          group_id?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      group_messages: {
        Row: {
          id: string
          group_id: string
          sender_id: string
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          group_id: string
          sender_id: string
          content: string
          created_at?: string
        }
        Update: {
          id?: string | null
          group_id?: string | null
          sender_id?: string | null
          content?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      group_nodes: {
        Row: {
          group_id: string
          node_id: string
          created_at: string
        }
        Insert: {
          group_id: string
          node_id: string
          created_at?: string
        }
        Update: {
          group_id?: string | null
          node_id?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      groups: {
        Row: {
          id: string
          name: string
          owner_id: string
          deleted_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          owner_id: string
          deleted_at: string | null
          created_at?: string
        }
        Update: {
          id?: string | null
          name?: string | null
          owner_id?: string | null
          deleted_at?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      messages: {
        Row: {
          id: string
          chat_id: string
          sender_id: string
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          chat_id: string
          sender_id: string
          content: string
          created_at?: string
        }
        Update: {
          id?: string | null
          chat_id?: string | null
          sender_id?: string | null
          content?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      node_classifications: {
        Row: {
          node_id: string
          owner_id: string
          theme: string | null
          subtheme: string | null
          channel_title: string | null
          updated_at: string
        }
        Insert: {
          node_id: string
          owner_id: string
          theme: string | null
          subtheme: string | null
          channel_title: string | null
          updated_at?: string
        }
        Update: {
          node_id?: string | null
          owner_id?: string | null
          theme?: string | null
          subtheme?: string | null
          channel_title?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      node_messages: {
        Row: {
          id: string
          node_id: string
          sender_id: string
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          node_id: string
          sender_id: string
          content: string
          created_at?: string
        }
        Update: {
          id?: string | null
          node_id?: string | null
          sender_id?: string | null
          content?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      node_notes: {
        Row: {
          id: string
          node_id: string
          user_id: string
          content: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          node_id: string
          user_id: string
          content?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string | null
          node_id?: string | null
          user_id?: string | null
          content?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      nodes: {
        Row: {
          id: string
          url: string | null
          text_content: string | null
          title: string | null
          thumbnail_key: string | null
          owner_id: string
          language_code: string
          origin_user_id: string
          origin_created_at: string
          deleted_at: string | null
          created_at: string
          node_type: string | null
          parent_node_id: string | null
          trash_batch_id: string | null
        }
        Insert: {
          id?: string
          url: string | null
          text_content: string | null
          title: string | null
          thumbnail_key: string | null
          owner_id: string
          language_code?: string
          origin_user_id: string
          origin_created_at?: string
          deleted_at: string | null
          created_at?: string
          node_type: string | null
          parent_node_id: string | null
          trash_batch_id: string | null
        }
        Update: {
          id?: string | null
          url?: string | null
          text_content?: string | null
          title?: string | null
          thumbnail_key?: string | null
          owner_id?: string | null
          language_code?: string | null
          origin_user_id?: string | null
          origin_created_at?: string | null
          deleted_at?: string | null
          created_at?: string | null
          node_type?: string | null
          parent_node_id?: string | null
          trash_batch_id?: string | null
        }
        Relationships: []
      }
      nodes_sort_cache: {
        Row: {
          node_id: string
          avg_rating: number | null
          view_count: number
          share_count: number
          updated_at: string
        }
        Insert: {
          node_id: string
          avg_rating: number | null
          view_count?: number
          share_count?: number
          updated_at?: string
        }
        Update: {
          node_id?: string | null
          avg_rating?: number | null
          view_count?: number | null
          share_count?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          payload: Json | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          payload: Json | null
          read?: boolean
          created_at?: string
        }
        Update: {
          id?: string | null
          user_id?: string | null
          type?: string | null
          payload?: Json | null
          read?: boolean | null
          created_at?: string | null
        }
        Relationships: []
      }
      organize_batches: {
        Row: {
          id: string
          user_id: string
          source_folder_id: string
          status: string
          created_at: string
          applied_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          source_folder_id: string
          status?: string
          created_at?: string
          applied_at: string | null
        }
        Update: {
          id?: string | null
          user_id?: string | null
          source_folder_id?: string | null
          status?: string | null
          created_at?: string | null
          applied_at?: string | null
        }
        Relationships: []
      }
      organize_items: {
        Row: {
          id: string
          batch_id: string
          node_id: string
          status: string
          target_folder_id: string | null
          new_folder_name: string | null
          tag_labels: any[]
          reason: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          batch_id: string
          node_id: string
          status?: string
          target_folder_id: string | null
          new_folder_name: string | null
          tag_labels?: any[]
          reason: string | null
          updated_at?: string
        }
        Update: {
          id?: string | null
          batch_id?: string | null
          node_id?: string | null
          status?: string | null
          target_folder_id?: string | null
          new_folder_name?: string | null
          tag_labels?: any[] | null
          reason?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      ratings: {
        Row: {
          id: string
          node_id: string
          user_id: string
          score: number
          updated_at: string
        }
        Insert: {
          id?: string
          node_id: string
          user_id: string
          score: number
          updated_at?: string
        }
        Update: {
          id?: string | null
          node_id?: string | null
          user_id?: string | null
          score?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      tag_edges: {
        Row: {
          id: string
          tag_id: string
          node_id: string | null
          folder_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tag_id: string
          node_id: string | null
          folder_id: string | null
          created_at?: string
        }
        Update: {
          id?: string | null
          tag_id?: string | null
          node_id?: string | null
          folder_id?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      tag_translations: {
        Row: {
          id: string
          tag_id: string
          language_code: string
          label: string
          created_at: string
        }
        Insert: {
          id?: string
          tag_id: string
          language_code: string
          label: string
          created_at?: string
        }
        Update: {
          id?: string | null
          tag_id?: string | null
          language_code?: string | null
          label?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      tags: {
        Row: {
          id: string
          color_hex: string
          created_at: string
        }
        Insert: {
          id?: string
          color_hex: string
          created_at?: string
        }
        Update: {
          id?: string | null
          color_hex?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      translations: {
        Row: {
          id: string
          node_id: string
          language_code: string
          title: string | null
          description: string | null
          created_at: string
        }
        Insert: {
          id?: string
          node_id: string
          language_code: string
          title: string | null
          description: string | null
          created_at?: string
        }
        Update: {
          id?: string | null
          node_id?: string | null
          language_code?: string | null
          title?: string | null
          description?: string | null
          created_at?: string | null
        }
        Relationships: []
      }
      user_node_preferences: {
        Row: {
          user_id: string
          scope_key: string
          node_id: string
          position: number
          updated_at: string
        }
        Insert: {
          user_id: string
          scope_key: string
          node_id: string
          position: number
          updated_at?: string
        }
        Update: {
          user_id?: string | null
          scope_key?: string | null
          node_id?: string | null
          position?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      users: {
        Row: {
          id: string
          display_name: string
          normalized_display_name: string
          language_code: string
          avatar_key: string | null
          username_changed_at: string | null
          avatar_change_count_today: number
          avatar_last_reset_date: string | null
          created_at: string
          onboarding_imported_at: string | null
          onboarding_dismissed_at: string | null
          youtube_import_consent_at: string | null
        }
        Insert: {
          id?: string
          display_name: string
          normalized_display_name: string
          language_code?: string
          avatar_key: string | null
          username_changed_at: string | null
          avatar_change_count_today?: number
          avatar_last_reset_date: string | null
          created_at?: string
          onboarding_imported_at: string | null
          onboarding_dismissed_at: string | null
          youtube_import_consent_at: string | null
        }
        Update: {
          id?: string | null
          display_name?: string | null
          normalized_display_name?: string | null
          language_code?: string | null
          avatar_key?: string | null
          username_changed_at?: string | null
          avatar_change_count_today?: number | null
          avatar_last_reset_date?: string | null
          created_at?: string | null
          onboarding_imported_at?: string | null
          onboarding_dismissed_at?: string | null
          youtube_import_consent_at?: string | null
        }
        Relationships: []
      }
      youtube_connections: {
        Row: {
          user_id: string
          google_account_email: string
          connected_at: string
          revoked_at: string | null
          access_token: string | null
          refresh_token: string | null
          token_expires_at: string | null
          scopes: any[] | null
          channel_id: string | null
          channel_title: string | null
          last_synced_at: string | null
          last_sync_error: string | null
        }
        Insert: {
          user_id: string
          google_account_email: string
          connected_at?: string
          revoked_at: string | null
          access_token: string | null
          refresh_token: string | null
          token_expires_at: string | null
          scopes: any[] | null
          channel_id: string | null
          channel_title: string | null
          last_synced_at: string | null
          last_sync_error: string | null
        }
        Update: {
          user_id?: string | null
          google_account_email?: string | null
          connected_at?: string | null
          revoked_at?: string | null
          access_token?: string | null
          refresh_token?: string | null
          token_expires_at?: string | null
          scopes?: any[] | null
          channel_id?: string | null
          channel_title?: string | null
          last_synced_at?: string | null
          last_sync_error?: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      _blocked_pair: {
        Args: {
        }
        Returns: any
      }
      _expand_folder_grants_for_folder: {
        Args: {
        }
        Returns: any
      }
      _expand_folder_grants_for_node: {
        Args: {
        }
        Returns: any
      }
      _expand_grant_on_scope: {
        Args: {
        }
        Returns: any
      }
      _folder_level: {
        Args: {
        }
        Returns: any
      }
      _node_visible: {
        Args: {
        }
        Returns: any
      }
      _notify_folder_item_added: {
        Args: {
        }
        Returns: any
      }
      _perm_name: {
        Args: {
        }
        Returns: any
      }
      _perm_rank: {
        Args: {
        }
        Returns: any
      }
      _resolve_auto_folder: {
        Args: {
        }
        Returns: any
      }
      _revoke_ancestor_grants_for_subtree: {
        Args: {
        }
        Returns: any
      }
      _revoke_folder_grants_for_node: {
        Args: {
        }
        Returns: any
      }
      _share_recipients: {
        Args: {
        }
        Returns: any[]
      }
      add_group_member: {
        Args: {
        }
        Returns: any
      }
      add_node_to_folder: {
        Args: {
        }
        Returns: any
      }
      add_tag_to_folder: {
        Args: {
        }
        Returns: any
      }
      add_tag_to_node: {
        Args: {
        }
        Returns: any
      }
      apply_organization_batch: {
        Args: {
        }
        Returns: any
      }
      block_user: {
        Args: {
        }
        Returns: any
      }
      change_folder_permission: {
        Args: {
        }
        Returns: any
      }
      change_node_permission: {
        Args: {
        }
        Returns: any
      }
      create_folder: {
        Args: {
        }
        Returns: any
      }
      create_folder_template: {
        Args: {
        }
        Returns: any
      }
      create_folder_with_nodes: {
        Args: {
        }
        Returns: any
      }
      create_group: {
        Args: {
          p_owner_id: string | null
          p_name: string | null
          p_member_ids: string[] | null
        }
        Returns: {
            id: string
            name: string
            owner_id: string
            deleted_at: string
            created_at: string
          }[]
      }
      create_node_with_metadata: {
        Args: {
          p_owner_id: string | null
          p_url: string | null
          p_text_content: string | null
          p_title: string | null
          p_thumbnail_key: string | null
          p_language_code: string | null
          p_tag_labels: string[] | null
          p_node_type: string | null
          p_description?: string | null
          p_auto_folder_name?: string | null
        }
        Returns: {
            id: string
            url: string
            text_content: string
            title: string
            thumbnail_key: string
            owner_id: string
            language_code: string
            origin_user_id: string
            origin_created_at: string
            deleted_at: string
            created_at: string
          }[]
      }
      create_organize_batch: {
        Args: {
        }
        Returns: any
      }
      create_tag_with_translation: {
        Args: {
        }
        Returns: any
      }
      delete_group: {
        Args: {
        }
        Returns: any
      }
      discard_organization_batch: {
        Args: {
        }
        Returns: any
      }
      effective_folder_permission: {
        Args: {
        }
        Returns: any
      }
      effective_node_permission: {
        Args: {
        }
        Returns: any
      }
      empty_trash: {
        Args: {
        }
        Returns: any
      }
      ensure_user_profile: {
        Args: {
        }
        Returns: any
      }
      folder_is_accessible: {
        Args: {
        }
        Returns: any
      }
      folder_is_owned: {
        Args: {
        }
        Returns: any
      }
      folder_is_visible: {
        Args: {
        }
        Returns: any
      }
      get_feed: {
        Args: {
          p_user_id: string | null
          p_language_code?: string | null
          p_view?: string | null
          p_friend_id?: string | null
          p_folder_id?: string | null
          p_group_id?: string | null
          p_filter_tag_ids?: string[] | null
          p_filter_friend_ids?: string[] | null
          p_filter_folder_ids?: string[] | null
          p_search_query?: string | null
          p_sort?: string | null
          p_cursor_created_at?: string | null
          p_cursor_node_id?: string | null
          p_limit?: number | null
          p_exclude_foldered?: boolean | null
          p_custom_order_ids?: string[] | null
        }
        Returns: {
            node_id: string
            url: string
            text_content: string
            title: string
            thumbnail_key: string
            owner_id: string
            language_code: string
            origin_user_id: string
            origin_created_at: string
            created_at: string
            avg_rating: number
            view_count: number
            share_count: number
            direction: string
            sender_id: string
            sender_name: string
            sender_avatar_key: string
            tags: Json
            total_count: number
          }[]
      }
      get_folder: {
        Args: {
          p_folder_id: string | null
        }
        Returns: {
            id: string
            name: string
            description: string
            owner_id: string
            owner_name: string
            parent_folder_id: string
            color_hex: string
            system_kind: string
            created_at: string
            my_permission: string
            is_shared: boolean
            breadcrumb: Json
            children: Json
            node_ids: string[]
          }[]
      }
      get_folder_access: {
        Args: {
          p_folder_id: string | null
        }
        Returns: {
            grantee_id: string
            display_name: string
            avatar_key: string
            permission: string
            granted_at: string
          }[]
      }
      get_folder_permission: {
        Args: {
        }
        Returns: any
      }
      get_folder_tree: {
        Args: {
          p_user_id: string | null
        }
        Returns: {
            id: string
            name: string
            description: string
            owner_id: string
            owner_name: string
            parent_folder_id: string
            is_project: boolean
            color_hex: string
            system_kind: string
            deleted_at: string
            created_at: string
            my_permission: string
          }[]
      }
      get_folders: {
        Args: {
          p_parent_folder_id?: string | null
          p_search?: string | null
          p_tag_ids?: string[] | null
          p_friend_id?: string | null
          p_sort?: string | null
        }
        Returns: {
            id: string
            name: string
            description: string
            owner_id: string
            owner_name: string
            parent_folder_id: string
            color_hex: string
            system_kind: string
            created_at: string
            my_permission: string
            is_shared: boolean
            node_count: number
            thumbnails: Json
          }[]
      }
      get_friend_bar: {
        Args: {
          p_user_id: string | null
        }
        Returns: {
            user_id: string
            display_name: string
            avatar_key: string
            to_email: string
            is_pending: boolean
            last_activity: string
          }[]
      }
      get_group_access_users: {
        Args: {
          p_group_id: string | null
        }
        Returns: {
            user_id: string
            display_name: string
            avatar_key: string
          }[]
      }
      get_node_access: {
        Args: {
          p_node_id: string | null
        }
        Returns: {
            user_id: string
            display_name: string
            avatar_key: string
            permission: string
            cause_id: string
            created_at: string
          }[]
      }
      get_node_friend_ratings: {
        Args: {
          p_node_id: string | null
          p_user_id: string | null
        }
        Returns: {
            user_id: string
            display_name: string
            avatar_key: string
            score: number
            updated_at: string
          }[]
      }
      get_node_permission: {
        Args: {
        }
        Returns: any
      }
      get_onboarding_import_node_ids: {
        Args: {
        }
        Returns: any
      }
      get_onboarding_state: {
        Args: {
        }
        Returns: any
      }
      get_or_create_named_folder: {
        Args: {
        }
        Returns: any
      }
      get_or_create_system_folder: {
        Args: {
        }
        Returns: any
      }
      get_organize_batch: {
        Args: {
          p_batch_id: string | null
        }
        Returns: {
            item_id: string
            node_id: string
            node_title: string
            node_thumbnail: string
            status: string
            target_folder_id: string
            target_folder_name: string
            new_folder_name: string
            tag_labels: string[]
            reason: string
          }[]
      }
      get_organize_batches: {
        Args: {
        }
        Returns: {
            id: string
            source_folder_id: string
            source_folder_name: string
            status: string
            item_count: number
            proposed_count: number
            created_at: string
          }[]
      }
      get_trash_count: {
        Args: {
        }
        Returns: any
      }
      get_trash_items: {
        Args: {
        }
        Returns: {
            item_type: string
            id: string
            title: string
            thumbnail_key: string
            trash_batch_id: string
            deleted_at: string
          }[]
      }
      get_unread_notification_count: {
        Args: {
        }
        Returns: any
      }
      get_user_folders: {
        Args: {
          p_user_id: string | null
        }
        Returns: {
            id: string
            name: string
            owner_id: string
            parent_folder_id: string
            is_project: boolean
            color_hex: string
            deleted_at: string
            created_at: string
            node_count: number
            thumbnails: Json
          }[]
      }
      get_visible_node_by_id: {
        Args: {
        }
        Returns: any[]
      }
      get_visible_tags: {
        Args: {
          p_user_id: string | null
          p_language_code?: string | null
        }
        Returns: {
            id: string
            color_hex: string
            label: string
          }[]
      }
      gin_extract_query_trgm: {
        Args: {
        }
        Returns: any
      }
      gin_extract_value_trgm: {
        Args: {
        }
        Returns: any
      }
      gin_trgm_consistent: {
        Args: {
        }
        Returns: any
      }
      gin_trgm_triconsistent: {
        Args: {
        }
        Returns: any
      }
      grant_folder_admin: {
        Args: {
        }
        Returns: any
      }
      grant_group_admin: {
        Args: {
        }
        Returns: any
      }
      group_is_member: {
        Args: {
        }
        Returns: any
      }
      group_is_owned: {
        Args: {
        }
        Returns: any
      }
      gtrgm_compress: {
        Args: {
        }
        Returns: any
      }
      gtrgm_consistent: {
        Args: {
        }
        Returns: any
      }
      gtrgm_decompress: {
        Args: {
        }
        Returns: any
      }
      gtrgm_distance: {
        Args: {
        }
        Returns: any
      }
      gtrgm_in: {
        Args: {
        }
        Returns: any
      }
      gtrgm_options: {
        Args: {
        }
        Returns: any
      }
      gtrgm_out: {
        Args: {
        }
        Returns: any
      }
      gtrgm_penalty: {
        Args: {
        }
        Returns: any
      }
      gtrgm_picksplit: {
        Args: {
        }
        Returns: any
      }
      gtrgm_same: {
        Args: {
        }
        Returns: any
      }
      gtrgm_union: {
        Args: {
        }
        Returns: any
      }
      hard_delete_folder: {
        Args: {
        }
        Returns: any
      }
      hard_delete_node: {
        Args: {
        }
        Returns: any
      }
      has_folder_permission: {
        Args: {
        }
        Returns: any
      }
      has_node_permission: {
        Args: {
        }
        Returns: any
      }
      import_url: {
        Args: {
          p_owner_id: string | null
          p_url: string | null
          p_title: string | null
          p_thumbnail_key: string | null
          p_language_code: string | null
          p_node_type: string | null
          p_description?: string | null
          p_new_tag_labels?: string[] | null
          p_existing_tag_ids?: string[] | null
          p_folder_id?: string | null
          p_note?: string | null
          p_auto_folder_name?: string | null
        }
        Returns: {
            id: string
            url: string
            text_content: string
            title: string
            thumbnail_key: string
            owner_id: string
            language_code: string
            origin_user_id: string
            origin_created_at: string
            deleted_at: string
            created_at: string
          }[]
      }
      increment_view_count: {
        Args: {
        }
        Returns: any
      }
      invite_friend: {
        Args: {
        }
        Returns: any
      }
      is_folder_admin: {
        Args: {
        }
        Returns: any
      }
      is_group_admin: {
        Args: {
        }
        Returns: any
      }
      liked_tag_palette: {
        Args: {
        }
        Returns: any
      }
      list_notifications: {
        Args: {
          p_limit?: number | null
          p_before?: string | null
        }
        Returns: {
            id: string
            type: string
            payload: Json
            read: boolean
            created_at: string
          }[]
      }
      mark_notifications_read: {
        Args: {
        }
        Returns: any
      }
      move_folder: {
        Args: {
        }
        Returns: any
      }
      move_node_everywhere: {
        Args: {
        }
        Returns: any
      }
      move_node_to_folder: {
        Args: {
        }
        Returns: any
      }
      nodes_guard_immutable_columns: {
        Args: {
        }
        Returns: any
      }
      rate_folder: {
        Args: {
        }
        Returns: any
      }
      remove_friend: {
        Args: {
        }
        Returns: any
      }
      remove_group_member: {
        Args: {
        }
        Returns: any
      }
      remove_node_from_folder: {
        Args: {
        }
        Returns: any
      }
      remove_tag_from_folder: {
        Args: {
        }
        Returns: any
      }
      remove_tag_from_node: {
        Args: {
        }
        Returns: any
      }
      rename_folder: {
        Args: {
        }
        Returns: any
      }
      restore_folder: {
        Args: {
        }
        Returns: any
      }
      restore_node: {
        Args: {
        }
        Returns: any
      }
      revoke_folder_grant: {
        Args: {
        }
        Returns: any
      }
      rls_auto_enable: {
        Args: {
        }
        Returns: any
      }
      set_custom_order: {
        Args: {
        }
        Returns: any
      }
      set_folder_color: {
        Args: {
        }
        Returns: any
      }
      set_folder_details: {
        Args: {
        }
        Returns: any
      }
      set_folder_grant_permission: {
        Args: {
        }
        Returns: any
      }
      set_language: {
        Args: {
        }
        Returns: any
      }
      set_limit: {
        Args: {
        }
        Returns: any
      }
      set_node_classifications: {
        Args: {
        }
        Returns: any
      }
      set_node_deleted: {
        Args: {
        }
        Returns: any
      }
      set_onboarding_flag: {
        Args: {
        }
        Returns: any
      }
      set_organize_item_proposal: {
        Args: {
        }
        Returns: any
      }
      set_youtube_import_consent: {
        Args: {
        }
        Returns: any
      }
      share_folder_v2: {
        Args: {
        }
        Returns: any
      }
      share_node: {
        Args: {
        }
        Returns: any
      }
      show_limit: {
        Args: {
        }
        Returns: any
      }
      show_trgm: {
        Args: {
        }
        Returns: any
      }
      similarity: {
        Args: {
        }
        Returns: any
      }
      similarity_dist: {
        Args: {
        }
        Returns: any
      }
      similarity_op: {
        Args: {
        }
        Returns: any
      }
      strict_word_similarity: {
        Args: {
        }
        Returns: any
      }
      strict_word_similarity_commutator_op: {
        Args: {
        }
        Returns: any
      }
      strict_word_similarity_dist_commutator_op: {
        Args: {
        }
        Returns: any
      }
      strict_word_similarity_dist_op: {
        Args: {
        }
        Returns: any
      }
      strict_word_similarity_op: {
        Args: {
        }
        Returns: any
      }
      trash_folder: {
        Args: {
        }
        Returns: any
      }
      unshare: {
        Args: {
        }
        Returns: any
      }
      update_avatar_key: {
        Args: {
          p_user_id: string | null
          p_avatar_key: string | null
        }
        Returns: {
            success: boolean
            error_code: string
          }[]
      }
      update_display_name: {
        Args: {
          p_user_id: string | null
          p_display_name: string | null
        }
        Returns: {
            success: boolean
            error_code: string
          }[]
      }
      update_node_text: {
        Args: {
        }
        Returns: any
      }
      update_node_title: {
        Args: {
        }
        Returns: any
      }
      upsert_card_position: {
        Args: {
        }
        Returns: any
      }
      upsert_rating: {
        Args: {
        }
        Returns: any
      }
      word_similarity: {
        Args: {
        }
        Returns: any
      }
      word_similarity_commutator_op: {
        Args: {
        }
        Returns: any
      }
      word_similarity_dist_commutator_op: {
        Args: {
        }
        Returns: any
      }
      word_similarity_dist_op: {
        Args: {
        }
        Returns: any
      }
      word_similarity_op: {
        Args: {
        }
        Returns: any
      }
    }
    Views: {}
    Enums: {}
    CompositeTypes: {}
  }
}
