-- ============================================================
-- Migration 089 — AUDIT-06 P2-10/P2-15: FK cascade + tag unique constraint
-- ============================================================
-- 1. Change FKs from default NO ACTION to ON DELETE CASCADE so deleting
--    a user/node/chat cascades properly (PRD: "deletion = cascade only").
-- 2. Change friend_invites.to_user_id from SET NULL to CASCADE.
-- 3. Add unique constraint on tag_translations(language_code, label)
--    to make createOrGetTag race-safe (the existing index
--    tag_translations_lookup_idx is non-unique).
--
-- FK constraint names are auto-generated by Postgres as <table>_<col>_fkey.
-- We drop and recreate them. Brief lock on each table during ALTER.
-- ============================================================

-- ── nodes.owner_id → CASCADE ──
ALTER TABLE nodes DROP CONSTRAINT IF EXISTS nodes_owner_id_fkey;
ALTER TABLE nodes ADD CONSTRAINT nodes_owner_id_fkey
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;

-- ── nodes.origin_user_id → CASCADE ──
ALTER TABLE nodes DROP CONSTRAINT IF EXISTS nodes_origin_user_id_fkey;
ALTER TABLE nodes ADD CONSTRAINT nodes_origin_user_id_fkey
  FOREIGN KEY (origin_user_id) REFERENCES users(id) ON DELETE CASCADE;

-- ── edges.node_id → CASCADE ──
ALTER TABLE edges DROP CONSTRAINT IF EXISTS edges_node_id_fkey;
ALTER TABLE edges ADD CONSTRAINT edges_node_id_fkey
  FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE;

-- ── edges.user_id → CASCADE ──
ALTER TABLE edges DROP CONSTRAINT IF EXISTS edges_user_id_fkey;
ALTER TABLE edges ADD CONSTRAINT edges_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- ── causes.created_by → CASCADE ──
ALTER TABLE causes DROP CONSTRAINT IF EXISTS causes_created_by_fkey;
ALTER TABLE causes ADD CONSTRAINT causes_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE;

-- ── folders.owner_id → CASCADE ──
ALTER TABLE folders DROP CONSTRAINT IF EXISTS folders_owner_id_fkey;
ALTER TABLE folders ADD CONSTRAINT folders_owner_id_fkey
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;

-- ── messages.chat_id → CASCADE ──
ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_chat_id_fkey;
ALTER TABLE messages ADD CONSTRAINT messages_chat_id_fkey
  FOREIGN KEY (chat_id) REFERENCES direct_chats(id) ON DELETE CASCADE;

-- ── friend_invites.to_user_id: SET NULL → CASCADE ──
ALTER TABLE friend_invites DROP CONSTRAINT IF EXISTS friend_invites_to_user_id_fkey;
ALTER TABLE friend_invites ADD CONSTRAINT friend_invites_to_user_id_fkey
  FOREIGN KEY (to_user_id) REFERENCES users(id) ON DELETE CASCADE;

-- ── tag_translations unique constraint on (language_code, label) ──
-- The existing tag_translations_lookup_idx is a non-unique index.
-- Add a unique constraint to prevent duplicate tag labels per language.
-- (tag_translations already has UNIQUE(tag_id, language_code), but we
-- also need UNIQUE(language_code, label) so two tags can't share the
-- same label in the same language.)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'tag_translations_language_code_label_key'
  ) THEN
    ALTER TABLE tag_translations
      ADD CONSTRAINT tag_translations_language_code_label_key
      UNIQUE (language_code, label);
  END IF;
END;
$$;
